//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class DISCOUNTCODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCOUNTCODE()
        {
            this.ORDERS = new HashSet<ORDER>();
            this.USERDISCOUNTs = new HashSet<USERDISCOUNT>();
        }
    
        public System.Guid DISCOUNT_ID { get; set; }

        [DisplayName("Mã giảm giá")]
        [Required(ErrorMessage = "Mã giảm giá không được để trống")]
        [MinLength(3, ErrorMessage = "Mã giảm giá phải có ít nhất {1} ký tự")]
        [MaxLength(20, ErrorMessage = "Vượt quá giới hạn ký tự")]
        [RegularExpression("^[a-zA-Z]*$", ErrorMessage = "Chỉ được nhập ký tự (char)")]
        public string CODE { get; set; }

        [DisplayName("Loại giảm giá")]
        [Required(ErrorMessage = "Loại giảm giá không được để trống")]
        public Nullable<bool> DISCOUNT_TYPE { get; set; }

        [DisplayName("Giá trị giảm giá")]
        [Required(ErrorMessage = "Giá trị giảm giá không được để trống")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Vui lòng nhập một số hợp lệ")]
        public Nullable<decimal> DISCOUNT_VALUE { get; set; }

        [DisplayName("Đơn hàng tối thiểu")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Vui lòng nhập một số hợp lệ")]
        public Nullable<decimal> MINIMUM_ORDER_AMOUNT { get; set; }

        [DisplayName("Ngày bắt đầu")]
        public Nullable<System.DateTime> START_DATE { get; set; }

        [DisplayName("Ngày kết thúc")]
        public Nullable<System.DateTime> END_DATE { get; set; }

        [DisplayName("Số lượng")]
        [Required(ErrorMessage = "Số lượng không được để trống")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Vui lòng nhập một số hợp lệ")]
        public Nullable<decimal> CODE_COUNT { get; set; }

        [DisplayName("Mô tả")]
        public string DESCRIPTION { get; set; }
        public bool DELETED { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERDISCOUNT> USERDISCOUNTs { get; set; }
    }
}
