//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLowerShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNTCODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISCOUNTCODE()
        {
            this.ORDERS = new HashSet<ORDER>();
            this.USERDISCOUNTs = new HashSet<USERDISCOUNT>();
        }
    
        public System.Guid DISCOUNT_ID { get; set; }
        public string CODE { get; set; }
        public Nullable<bool> DISCOUNT_TYPE { get; set; }
        public Nullable<decimal> DISCOUNT_VALUE { get; set; }
        public Nullable<decimal> MINIMUM_ORDER_AMOUNT { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> CODE_COUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public bool DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERDISCOUNT> USERDISCOUNTs { get; set; }
    }
}
