//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FLOWERTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLOWERTYPE()
        {
            this.FLOWERS = new HashSet<FLOWER>();
        }
    
        public System.Guid FLOWERTYPE_ID { get; set; }
        [DisplayName("Tên loại hoa")]
        [Required(ErrorMessage = "Tên không được để trống")]
        [StringLength(100, ErrorMessage = "Tên phải có ít nhât {2} ký tự và không quá 100 ký tự.", MinimumLength = 5)]
        public string FLOWERTYPE_NAME { get; set; }
        public bool DELETED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FLOWER> FLOWERS { get; set; }
    }
}
