//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLowerShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOWER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLOWER()
        {
            this.SHOPPINGCARTs = new HashSet<SHOPPINGCART>();
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public System.Guid FLOWER_ID { get; set; }
        public string FLOWER_NAME { get; set; }
        public string FLOWER_IMAGE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> OLD_PRICE { get; set; }
        public Nullable<decimal> NEW_PRICE { get; set; }
        public Nullable<System.Guid> FLOWERTYPE_ID { get; set; }
        public bool DELETED { get; set; }
    
        public virtual FLOWERTYPE FLOWERTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOPPINGCART> SHOPPINGCARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
    }
}
