//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLowerShop.Context
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERHISTORies = new HashSet<ORDERHISTORY>();
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }

        [DisplayName("Mã đặt hàng")]
        public System.Guid ORDER_ID { get; set; }

        [DisplayName("Mã người dùng")]
        public System.Guid USER_ID { get; set; }

        [DisplayName("Ngày đặt hàng")]
        public Nullable<System.DateTime> ORDER_DATE { get; set; }

        [DisplayName("Tổng tiền")]
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }

        public System.Guid DISCOUNT_ID { get; set; }


        [DisplayName("Lời nhắn [Cho người nhận]:")]
        public string MESSAGE_TO_RECIPIENT { get; set; }

        [DisplayName("Yêu cầu, lưu ý [Cho BloomShop]:")]
        public string MESSAGE_TO_SHOP { get; set; }

        [DisplayName("Ẩn thông tin")]
        public Nullable<bool> HIDE_SENDER_INFO { get; set; }

        [DisplayName("Hình thức thanh toán")]
        public Nullable<bool> PAYMENT_METHOD { get; set; }

        [DisplayName("Trạng thái thanh toán")]
        public Nullable<bool> IS_PAID { get; set; }

        [DisplayName("Họ tên:")]
        [MinLength(1, ErrorMessage = "Tên phải có từ 1 đến 32 ký tự!")]
        [MaxLength(32, ErrorMessage = "Tên phải có từ 1 đến 32 ký tự!")]
        [Required(ErrorMessage = "Vui lòng nhập tên")]
        public string RECIPIENT_NAME { get; set; }

        [DisplayName("Điện thoại:")]
        [MinLength(10, ErrorMessage = "Điện thoại phải có từ 10 đến 12 số!")]
        [MaxLength(12, ErrorMessage = "Điện thoại phải có từ 10 đến 12 số!")]
        [Required(ErrorMessage ="Vui lòng nhập SĐT")]
        public string RECIPIENT_PHONE { get; set; }

        [DisplayName("Địa chỉ:")]
        [MinLength(3, ErrorMessage = "Địa chỉ 1 phải có từ 3 đến 128 ký tự!")]
        [MaxLength(128, ErrorMessage = "Địa chỉ 1 phải có từ 3 đến 128 ký tự!")]
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        public string RECIPIENT_ADDRESS { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual DISCOUNTCODE DISCOUNTCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERHISTORY> ORDERHISTORies { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
    }
}
