//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLowerShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDERHISTORies = new HashSet<ORDERHISTORY>();
            this.ORDERDETAILS = new HashSet<ORDERDETAIL>();
        }
    
        public System.Guid ORDER_ID { get; set; }
        public System.Guid USER_ID { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public System.Guid DISCOUNT_ID { get; set; }
        public string MESSAGE_TO_RECIPIENT { get; set; }
        public string MESSAGE_TO_SHOP { get; set; }
        public Nullable<bool> HIDE_SENDER_INFO { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public Nullable<bool> IS_PAID { get; set; }
        public string RECIPIENT_NAME { get; set; }
        public string RECIPIENT_PHONE { get; set; }
        public string RECIPIENT_ADDRESS { get; set; }
        public Nullable<bool> DELETED { get; set; }
        public System.Guid CART_ID { get; set; }
    
        public virtual DISCOUNTCODE DISCOUNTCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERHISTORY> ORDERHISTORies { get; set; }
        public virtual USER USER { get; set; }
        public virtual SHOPPINGCART SHOPPINGCART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDERDETAIL> ORDERDETAILS { get; set; }
    }
}
