//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLowerShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOPPINGCART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHOPPINGCART()
        {
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public System.Guid CART_ID { get; set; }
        public System.Guid USER_ID { get; set; }
        public System.Guid FLOWER_ID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<bool> DELETED { get; set; }
    
        public virtual FLOWER FLOWER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
        public virtual USER USER { get; set; }
    }
}
