//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowerShop.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERDISCOUNT
    {
        public System.Guid USERDISCOUNT_ID { get; set; }
        public Nullable<System.Guid> USER_ID { get; set; }
        public Nullable<System.Guid> DISCOUNT_ID { get; set; }
        public bool DELETED { get; set; }
    
        public virtual DISCOUNTCODE DISCOUNTCODE { get; set; }
        public virtual USER USER { get; set; }
    }
}
